---
- hosts: localhost
  remote_user: "{{ remote_user }}"
  pre_tasks:
    - include_vars: ../defaults/main.yml
  roles:
    - aws

- hosts: metrics
  remote_user: "{{ remote_user }}"
  become: yes
  become_method: sudo
  pre_tasks:
    - include_vars: ../defaults/main.yml
  roles:
    - common
    - influx
    - grafana
    - riemann
    - collectd

- hosts: zookeeper
  remote_user: "{{ remote_user }}"
  become: yes
  become_method: sudo
  pre_tasks:
    - include_vars: ../defaults/main.yml
  roles:
    - common
    - zookeeper
    - collectd

- hosts: peer
  remote_user: "{{ remote_user }}"
  become: yes
  become_method: sudo
  pre_tasks:
    - include_vars: ../defaults/main.yml
  vars:
    - prepare_onyx: yes
  roles:
    - common
    - collectd
    - onyx_peers
