---
- name: Create the directory for collectd
  file:
    path: /srv/collectd
    state: directory
    mode: 0755
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
    recurse: yes

- name: Create the config directory for collectd
  file:
    path: /etc/collectd
    state: directory
    mode: 0755
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
    recurse: yes

- name: Download build-essential
  package:
    name: "{{ item }}"
  with_items:
    - build-essential
    - libprotobuf-c0-dev
    - protobuf-c-compiler
    - librrd-dev
    - libltdl-dev

- name: Download collectd
  unarchive:
    src: https://collectd.org/files/collectd-5.5.0.tar.gz
    dest: /srv/collectd
    copy: no

- name: Configure collectd
  shell: ./configure
  args:
    chdir: /srv/collectd/collectd-5.5.0

- name: Install collectd
  shell: make all install
  args:
    chdir: /srv/collectd/collectd-5.5.0
  become: yes

- name: Install collectd config
  template:
    src: collectd.conf.j2
    dest: /etc/collectd/collectd.conf
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
    mode: 0555

- name: Touch a config file needed for collectd
  file:
    path: /etc/collectd/thresholds.conf
    state: touch
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
    mode: 0555

- name: Restart collectd if possible
  shell: killall -2 collectd || true
  become: yes

- name: Start collectd
  shell: /opt/collectd/sbin/collectd -C /etc/collectd/collectd.conf
  become: yes